Lettera n
FreeNAS-Italian-Translation-Team/webui pull request #20
Opened 2020-06-30 14:27 UTC by lucamolteni

2020-06-30 15:27 UTC, proto requested changes
Qualche typo ancora, ma ci siamo.

2020-06-30 15:31 UTC, proto commented on src/assets/i18n/it.po
> +"to the Internet with other systems on the network."
```suggestion
"Network Address Translation (NAT). Traduce gli indirizzi IP locali "
"in un singolo indirizzo IP. Impostare quando la jail condividerà un'unica "
"connessione a Internet con altri sistemi sulla rete."
```

2020-06-30 15:33 UTC, proto commented on src/assets/i18n/it.po
> +"premendo      <code>Enter</code>."
```suggestion
"Indirizzi di rete che possono usare questo initiatior. Lascia vuoto per permettere a    "
"   tutti gli indirizzi o elenca gli indirizzi di rete con maschera CIDR. Separa i valori "
"premendo      <code>Enter</code>."
```

in sostanza: o vuoto o 10.10.10.0/27 per esempio.

2020-06-30 15:34 UTC, proto commented on src/assets/i18n/it.po
> +msgstr "Nomeserver 1"
```suggestion
msgstr "Nameserver 1"
```

sono i DNS, possiamo lasciarli in EN

2020-07-01 14:57 UTC, Hitman86R commented on src/assets/i18n/it.po
> +msgstr "Nomeserver 1"
Concordo, meglio lasciare nameserver

2020-07-01 14:59 UTC, Hitman86R approved these changes

2020-07-02 14:12 UTC, lucamolteni commented
Sistemato mergiamo allora?

2020-07-02 14:24 UTC, proto commented
> Sistemato mergiamo allora?

per me ok!

temo di combinare guai con questo tool modernissimo, per cui... fate voi, per cortesia : - )

2020-07-02 14:25 UTC, proto approved these changes

2020-07-02 14:28 UTC, merged