Lettera D - e due
FreeNAS-Italian-Translation-Team/webui pull request #5
Opened 2020-06-20 17:07 UTC by proto

Ok. provo PR dal mio branch.

**"Can’t automatically merge. Don’t worry, you can still create the pull request."**

2020-06-22 08:19 UTC, lucamolteni commented
@proto ho già visto che la PR non va bene, tra i file changed dovresti vedere solo il tuo file di traduzione. Questo perché probabilmente il tuo branch è più vecchio rispetto al fork di `FreeNAS-Italian-Translation-Team:master`

Esegui dal tuo branch i seguenti comandi

`git fetch upstream`
`git rebase upstream master`

se tutto va correttamente dovresti avere pochi commit sopra  a tutto il resto. 
Solo a quel punto puoi fare 

`git push --force`

Sentiamoci di persona per farlo in chat, dimmi tu quando

2020-06-22 08:19 UTC, lucamolteni requested changes
Rebase this

2020-06-22 09:12 UTC, proto commented
> @proto ho già visto che la PR non va bene, tra i file changed dovresti vedere solo il tuo file di traduzione. Questo perché probabilmente il tuo branch è più vecchio rispetto al fork di `FreeNAS-Italian-Translation-Team:master`
> 
> Esegui dal tuo branch i seguenti comandi
> 
> `git fetch upstream`
> `git rebase upstream master`
> 
> se tutto va correttamente dovresti avere pochi commit sopra a tutto il resto.
> Solo a quel punto puoi fare
> 
> `git push --force`
> 
> Sentiamoci di persona per farlo in chat, dimmi tu quando

e' vero.  : - /

2020-06-23 07:15 UTC, proto commented
la chiudo e provo a risottomettere

2020-06-23 07:15 UTC, closed without merging